### ISSUE TITLE
Print credentials

### ISSUE THREAD

**Issue by jsanz** [CartoDB/labs-postgresql#19]
We need to generate a spreadsheet of all users API keys to provide them at the beginning of the workshop, a report for the `cartoworkshops` CARTO organization should be enough to remove everithing but the `commitconf-{03..30}` accounts since `01` is for us and I used `02` for testing the exercises.

Unfortunately the [enterprise user management API](https://carto.com/help/your-account/enterprise-api/) does not provide API keys so I need you @alrocar to do that :smile:

**Comment by alrocar** [comment]
From the Rails console:

```ruby
require 'csv'

org_name = 'cartoworkshops'
CSV.open("/tmp/api_keys.csv", "w") do |csv|
  csv << ["user", "api_key"]
  Organization.where(name: org_name).first.users.sort_by(&:username).each do |user|
    csv << [user.username, user.api_key]
  end
end
```
